server:
  port: 8201
spring:
  datasource:
    url: jdbc:mysql://39.107.243.186:3306/traffic_survey?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: traffic_survey
    password: sutpc123
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
      database: 2
      host: 39.107.243.186
      port: 6379
      password:
      timeout: 5000
  jackson:
    #日期格式化
    date-format: yyyyMMddHHmmss
    serialization:
      #格式化输出
      indent_output: true
      #忽略无法转换的对象
      fail_on_empty_beans: false  # 对象为空时不报错
    #设置空如何序列化
    defaultPropertyInclusion: NON_EMPTY
    deserialization:
      #允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false
    parser:
      #允许出现特殊字符和转义符
      allow_unquoted_control_chars: true
      #允许出现单引号
      allow_single_quotes: true
    # 设置属性命名策略,对应jackson下PropertyNamingStrategy中的常量值，SNAKE_CASE-返回的json驼峰式转下划线，json body下划线传到后端自动转驼峰式
    property-naming-strategy: SNAKE_CASE

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true #返回map类型时下划线怎么转驼峰命名，但是需要resultMap 对应相应的entity类，否则无法转换

logging:
  config:
    classpath: logback.xml
#保存log文件路径在logback.xml中配置

com:
  sutpc:
    version: 0.0.1




